default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.dig(:db, :user) %>
  password: <%= Rails.application.credentials.dig(:db, :password) %>

development:
  <<: *default
  database: <%= "#{ENV['DB_PREFIX']}development" %>

test:
  <<: *default
  database: <%= "#{ENV['DB_PREFIX']}test" %>

production:
  <<: *default
  database: <%= "#{ENV['DB_PREFIX']}production" %>
